// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU2UwSa20CwH-vlYwhPPRHz6WLPTydQ4g',
    appId: '1:218911010408:android:048ba2398f087f359655dd',
    messagingSenderId: '218911010408',
    projectId: 'flutter-login-app-2dc0d',
    storageBucket: 'flutter-login-app-2dc0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbIQ2SyP3ZiZX_Z2GOctFJUWhOcOtdScY',
    appId: '1:218911010408:ios:f3526cf1ef3a64a19655dd',
    messagingSenderId: '218911010408',
    projectId: 'flutter-login-app-2dc0d',
    storageBucket: 'flutter-login-app-2dc0d.appspot.com',
    androidClientId: '218911010408-6tqfnv9t0c8gb3irpvuftcgj79rrecm3.apps.googleusercontent.com',
    iosClientId: '218911010408-0b3k0hccd4m6gjeeofc14guk36cm828j.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );
}
